apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: k8s.jevic.com/demo/demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
