apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-sts
  labels:
    app: myapp-sts
spec:
  serviceName: myapp-sts
  replicas: 1
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: myapp
        image: jevic/app:v1
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-sts-svc
spec:
  selector:
    app: myapp-sts
  ports:
    - port: 80
  clusterIP: None