apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    creator: norman
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /data/nfs/web
    server: 192.168.2.243
  persistentVolumeReclaimPolicy: Retain
