apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  labels:
    app: volume-app
    tier: frontend
  annotations:
    jevic.cn/created-by: "cluster admin"
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 7200"
    volumeMounts:
    - name: html
      mountPath: /data/web/html
  volumes:
  - name: html
    emptyDir: {}
