apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-www
  namespace: default
data:
  www.conf: |
    server {
           listen 80;
           server_name myapp.jevic.cn;
           location / {
           root /data/nginx/html;
           }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-cm2
  labels:
    app: myapp-cm2
spec:
  containers:
  - name: myapp-cm2
    image: jevic/app:v1
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginxconf
      mountPath: /etc/nginx/conf.d/
      readOnly: true
  volumes:
  - name: nginxconf
    configMap:
      name: nginx-www
